spring.application.name=ProjetoExemplo
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=${JWT_SECRET}
