spring.application.name=ProjetoExemplo
server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.ctznqkiledxnymyeiypg&password=qXN0mgIupTicdqlx&prepareThreshold=0
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=H1%74eR3I4
