# ALTERE COM OS DADOS DO SEU PROJETO E BANCO DE DADOS
spring.application.name=ProjetoExemplo
# Porta em que a aplicação Spring Boot será executada.
server.port=${PORT}
# Cuidado com caracteres especiais na senha, como '#', etc.
# Quando usar o pooler de conexões, incluir o parâmetro 'prepareThreshold=0' para evitar problemas de preparação de consultas.
spring.datasource.url=${DATABASE_URL}
# Esquema de criação do banco de dados: 'create' para criar as tabelas a cada execução, 'update' para atualizar o esquema.
spring.jpa.hibernate.ddl-auto=validate
# Exibe as consultas SQL no console para depuração.
spring.jpa.show-sql=true
# Define o dialeto do Hibernate para PostgreSQL, garantindo compatibilidade com as funcionalidades espec?ficas do banco de dados.
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}
api.security.token.secret=${SECURITY_SECRET}
cloudinary.url=${CLOUDINARY_URL}










